on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Check the Git repository.
        uses: actions/checkout@v2

      - name: Install node with version.
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Installing the dependencies.
        run: npm install

      - name: Running lint to check for errors.
        run: npx eslint . --ext .tsx --ext .ts

  tests-e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Check the Git repository
        uses: actions/checkout@v2

      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          build: npm run build
          start: npm run start
          wait-on: http://localhost:3000
        env:
            NEXT_PUBLIC_API_URL: ${{secrets.NEXT_PUBLIC_API_URL}}